Clean up docs.yml and check-external-types.yml

diff --git a/.github/workflows/check-external-types.yml b/.github/workflows/check-external-types.yml
--- a/.github/workflows/check-external-types.yml
+++ b/.github/workflows/check-external-types.yml
@@ -3,15 +3,14 @@ permissions:
 
 on:
   workflow_call:
-    # TODO: add crates input?
     inputs:
       rust:
         required: false
         type: string
         default: nightly-2022-11-16
-      target:
-        required: false
-        type: string
+      # target:
+      #   required: false
+      #   type: string
       args:
         required: false
         type: string
@@ -40,11 +39,68 @@ jobs:
           persist-credentials: false
       - name: Install Rust
         run: rustup toolchain add ${{ inputs.rust }} --no-self-update --profile minimal && rustup default ${{ inputs.rust }}
-      - run: |
-          rustup target add ${{ inputs.target }}
-          echo "TARGET=--target=${{ inputs.target }}" >>"${GITHUB_ENV}"
-        if: inputs.target != ''
       - uses: taiki-e/cache-cargo-install-action@v1
         with:
           tool: cargo-check-external-types@0.1.6
-      - run: cargo check-external-types --all-features --config .external-types.toml $TARGET ${{ inputs.args }}
+      # See https://docs.rs/about/metadata for docs.rs metadata.
+      # See https://github.com/awslabs/cargo-check-external-types/blob/v0.1.6/src/main.rs#L54 for cargo-check-external-types options.
+      # NB: sync with docs.yml
+      # TODO: move this script to its own file to apply shfmt and shellcheck.
+      - name: Run cargo check-external-types
+        run: |
+          set -euo pipefail
+          # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
+          base_args=(${{ inputs.args }})
+          IFS=$'\n\t'
+          metadata=$(cargo metadata --format-version=1 --all-features --no-deps)
+          # TODO: check-external-types doesn't support --target flag
+          # # Handle target inputs.
+          # input_target="${{ inputs.target }}"
+          # if [[ -n "${input_target}" ]]; then
+          #   while read -rd,; do
+          #     base_args+=(--target="${REPLY}")
+          #     rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
+          #   done <<<"${input_target},"
+          # fi
+          # Run cargo check-external-types for public crates with features specified in docs.rs metadata in Cargo.toml.
+          for id in $(jq <<<"${metadata}" '.workspace_members[]'); do
+            args=("${base_args[@]}")
+            pkg=$(jq <<<"${metadata}" ".packages[] | select(.id == ${id})")
+            publish=$(jq <<<"${pkg}" -r '.publish')
+            # Publishing is unrestricted if null, and forbidden if an empty array.
+            if [[ "${publish}" == "[]" ]]; then
+              continue
+            fi
+            manifest_path=$(jq <<<"${pkg}" -r '.manifest_path')
+            args+=(--manifest-path="${manifest_path}")
+            # TODO: check-external-types doesn't support --target flag
+            # # Respect target-related fields specified in docs.rs metadata if inputs.target is empty.
+            # if [[ -z "${input_target}" ]]; then
+            #   default_target="$(jq <<<"${pkg}" '.metadata.docs.rs."default-target"')"
+            #   if [[ "${default_target}" != null ]]; then
+            #     args+=(--target="${default_target}")
+            #     rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+            #   fi
+            #   if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs.targets')" != null ]]; then
+            #     for target in $(jq <<<"${pkg}" -r '.metadata.docs.rs.targets[]'); do
+            #       args+=(--target="${target}")
+            #       rustup target add "${target}" || true # tier 3 targets fail to install rustup target
+            #     done
+            #   fi
+            # fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs.features')" != null ]]; then
+              for feature in $(jq <<<"${pkg}" -r '.metadata.docs.rs.features[]'); do
+                args+=(--features="${feature}")
+              done
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."all-features"')" == 'true' ]]; then
+              args+=(--all-features)
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."no-default-features"')" == 'true' ]]; then
+              args+=(--no-default-features)
+            fi
+            (
+              set -x
+              cargo check-external-types --config .external-types.toml "${args[@]}"
+            )
+          done
diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -39,24 +39,31 @@ jobs:
           persist-credentials: false
       - name: Install Rust
         run: rustup toolchain add ${{ inputs.rust }} --no-self-update --profile minimal && rustup default ${{ inputs.rust }}
-      # TODO: respect target field in docs.rs metadata if inputs.target is empty.
+      # See https://docs.rs/about/metadata for docs.rs metadata.
+      # NB: sync with check-external-types.yml
       # TODO: move this script to its own file to apply shfmt and shellcheck.
       - name: Run cargo doc
         run: |
           set -euo pipefail
           # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
-          args=(-Z unstable-options -Z rustdoc-scrape-examples --document-private-items ${{ inputs.args }})
+          base_args=(-Z unstable-options -Z rustdoc-scrape-examples --document-private-items ${{ inputs.args }})
+          base_rustflags="${RUSTFLAGS:-}"
+          base_rustdocflags="${RUSTDOCFLAGS:-} -Z unstable-options --document-hidden-items"
           IFS=$'\n\t'
-          # Handle target flags.
-          if [[ -n "${{ inputs.target }}" ]]; then
-            while read -rd,; do
-              args+=("--target=${REPLY}")
-              rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
-            done <<<"${{ inputs.target }},"
-          fi
-          # Run cargo doc for public crates with features in docs.rs metadata in Cargo.toml.
           metadata=$(cargo metadata --format-version=1 --all-features --no-deps)
+          # Handle target inputs.
+          input_target="${{ inputs.target }}"
+          if [[ -n "${input_target}" ]]; then
+            while read -rd,; do
+              base_args+=(--target="${REPLY}")
+              rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
+            done <<<"${input_target},"
+          fi
+          # Run cargo doc for public crates with features and rustc/rustdoc/cargo args specified in docs.rs metadata in Cargo.toml.
           for id in $(jq <<<"${metadata}" '.workspace_members[]'); do
+            args=("${base_args[@]}")
+            pkg_rustflags="${base_rustflags}"
+            pkg_rustdocflags="${base_rustdocflags}"
             pkg=$(jq <<<"${metadata}" ".packages[] | select(.id == ${id})")
             publish=$(jq <<<"${pkg}" -r '.publish')
             # Publishing is unrestricted if null, and forbidden if an empty array.
@@ -64,27 +71,57 @@ jobs:
               continue
             fi
             manifest_path=$(jq <<<"${pkg}" -r '.manifest_path')
-            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."all-features"')" == 'true' ]]; then
-              (
-                set -x
-                cargo doc --manifest-path "${manifest_path}" --all-features "${args[@]}"
-              )
-            elif [[ "$(jq <<<"${pkg}" '.metadata.docs.rs.features')" != null ]]; then
-              feature_flags=()
-              for feature in $(jq <<<"${pkg}" -r '.metadata.docs.rs.features[]'); do
-                  feature_flags+=(--features="${feature}")
-              done
-              (
-                set -x
-                cargo doc --manifest-path "${manifest_path}" "${feature_flags[@]}" "${args[@]}"
-              )
-            else
-              (
-                set -x
-                cargo doc --manifest-path "${manifest_path}" "${args[@]}"
-              )
+            args+=(--manifest-path="${manifest_path}")
+            # Respect target-related fields specified in docs.rs metadata if inputs.target is empty.
+            if [[ -z "${input_target}" ]]; then
+              default_target="$(jq <<<"${pkg}" '.metadata.docs.rs."default-target"')"
+              if [[ "${default_target}" != null ]]; then
+                args+=(--target="${default_target}")
+                rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+              fi
+              if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs.targets')" != null ]]; then
+                for target in $(jq <<<"${pkg}" -r '.metadata.docs.rs.targets[]'); do
+                  args+=(--target="${target}")
+                  rustup target add "${target}" || true # tier 3 targets fail to install rustup target
+                done
+              fi
             fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs.features')" != null ]]; then
+              for feature in $(jq <<<"${pkg}" -r '.metadata.docs.rs.features[]'); do
+                args+=(--features="${feature}")
+              done
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."all-features"')" == 'true' ]]; then
+              args+=(--all-features)
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."no-default-features"')" == 'true' ]]; then
+              args+=(--no-default-features)
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."rustc-args"')" != null ]]; then
+              for arg in $(jq <<<"${pkg}" -r '.metadata.docs.rs."rustc-args"[]'); do
+                pkg_rustflags+=" ${arg}"
+              done
+              export RUSTFLAGS="${pkg_rustflags}"
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."rustdoc-args"')" != null ]]; then
+              for arg in $(jq <<<"${pkg}" -r '.metadata.docs.rs."rustdoc-args"[]'); do
+                pkg_rustdocflags+=" ${arg}"
+              done
+              export RUSTDOCFLAGS="${pkg_rustdocflags}"
+            fi
+            if [[ "$(jq <<<"${pkg}" '.metadata.docs.rs."cargo-args"')" != null ]]; then
+              for arg in $(jq <<<"${pkg}" -r '.metadata.docs.rs."cargo-args"[]'); do
+                args+=("${arg}")
+              done
+            fi
+            if [[ -n "${RUSTFLAGS:-}" ]]; then
+              echo "+ RUSTFLAGS='${RUSTFLAGS}' \\"
+            fi
+            if [[ -n "${RUSTDOCFLAGS:-}" ]]; then
+              echo "+ RUSTDOCFLAGS='${RUSTDOCFLAGS}' \\"
+            fi
+            (
+              set -x
+              cargo doc "${args[@]}"
+            )
           done
-        env:
-          RUSTFLAGS: ${{ env.RUSTFLAGS }} --cfg docsrs
-          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} --cfg docsrs -Z unstable-options --document-hidden-items
